version: "3.0"
services:
        nginx:
                build: 
                        dockerfile: 'nginx/Dockerfile'
                        context: '.'
                hostname: 'nginx'
                ports:
                - "80:80"
                restart: 'always'
                depends_on:
                        - gamification
        gamification:
                build: .
                hostname: 'gamification'
                restart: 'always'
