# Generated by Django 3.1.6 on 2021-02-21 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('username', models.TextField(primary_key=True, serialize=False)),
                ('solves', models.TextField(default='{}', null=True)),
                ('fruit', models.TextField(default='', null=True)),
                ('eyes', models.TextField(default='', null=True)),
                ('head', models.TextField(default='', null=True)),
                ('nose', models.TextField(default='', null=True)),
                ('mouth', models.TextField(default='', null=True)),
                ('carry', models.TextField(default='', null=True)),
                ('score', models.IntegerField(default=0, null=True)),
            ],
        ),
    ]
