# Generated by Django 3.1.2 on 2020-11-16 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('username', models.TextField(primary_key=True, serialize=False)),
                ('solves', models.TextField(default='{}', null=True)),
                ('fruit', models.TextField(default='', null=True)),
                ('face', models.TextField(default='', null=True)),
                ('hat', models.TextField(default='', null=True)),
                ('shoe', models.TextField(default='', null=True)),
                ('sunglasses', models.TextField(default='', null=True)),
                ('tools', models.TextField(default='', null=True)),
                ('wig', models.TextField(default='', null=True)),
                ('accessories', models.TextField(default='', null=True)),
                ('score', models.IntegerField(default=0, null=True)),
            ],
        ),
    ]
