# Generated by Django 3.1.2 on 2020-11-16 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='accessories',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='face',
            new_name='carry',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='hat',
            new_name='head',
        ),
        migrations.RemoveField(
            model_name='player',
            name='sunglasses',
        ),
        migrations.RemoveField(
            model_name='player',
            name='tools',
        ),
        migrations.RemoveField(
            model_name='player',
            name='wig',
        ),
    ]
